// examples/angular/src/app/components/transfer/transfer.component.ts
import { Component, inject } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { UserService } from '../../services/user/user.service';

@Component({
  selector: 'app-transfer',
  imports: [ReactiveFormsModule],
  templateUrl: './transfer.component.html',
  standalone: true,
  host: {
    class: 'p-8 flex items-center justify-center bg-white',
  },
})
export class TransferComponent {
  protected user = inject(UserService);
  protected actor = this.user.actor.asReadonly();

  readonly toControl = new FormControl<string>('', { nonNullable: true });
  readonly amountControl = new FormControl<string>('', { nonNullable: true });

  async transfer() {
    await this.user.transfer(this.toControl.value, this.amountControl.value);
  }
}

<div class="w-full max-w-xs mx-auto space-y-4">
  <div>
    <label for="email"
           class="flex text-sm font-medium text-gray-700">From</label>
    <div class="mt-1">
      <input id="from-input"
             type="text"
             name="from"
             id="from"
             class="shadow-sm border focus:ring focus:ring-purple-500 focus:border-purple-500 block w-full sm:text-sm border-gray-300 rounded-md px-3 py-2 outline-none"
             disabled="true"
             placeholder="Please login"
             [value]="actor()" />
    </div>
  </div>

  <div>
    <label for="email"
           class="flex text-sm font-medium text-gray-700">To</label>
    <div class="mt-1">
      <input id="to-input"
             type="text"
             name="to"
             class="shadow-sm border focus:ring focus:ring-purple-500 focus:border-purple-500 block w-full sm:text-sm border-gray-300 rounded-md px-3 py-2 outline-none"
             placeholder="e.g. token.burn"
             [formControl]="toControl" />
    </div>
  </div>
  <div>
    <label for="email"
           class="flex text-sm font-medium text-gray-700">Amount</label>
    <div class="mt-1">
      <input id="amount-input"
             type="text"
             name="amount"
             class="shadow-sm border focus:ring focus:ring-purple-500 focus:border-purple-500 block w-full sm:text-sm border-gray-300 rounded-md px-3 py-2 outline-none"
             placeholder="e.g. 1.3"
             [formControl]="amountControl" />
    </div>
  </div>

  <div class="flex justify-center">
    <button id="transfer-button"
            class="whitespace-nowrap bg-purple-100 border border-transparent rounded-md py-2 px-4 inline-flex items-center justify-center text-base font-medium text-purple-600 hover:bg-purple-200"
            (click)="transfer()"
            [disabled]="!actor()">
      Transfer
    </button>
  </div>
</div>

// examples/svelte/src/lib/components/Transfer.svelte
<script lang="ts">
	import { transfer, actor } from '$lib/userState';

	let to = '';
	let amount = '';
</script>

<div class="p-8 flex items-center justify-center bg-white">
	<div class="w-full max-w-xs mx-auto space-y-4">
		<div>
			<label for="email" class="flex text-sm font-medium text-gray-700">From</label>
			<div class="mt-1">
				<input
					type="text"
					name="from"
					id="from"
					class="shadow-sm border focus:ring focus:ring-purple-500 focus:border-purple-500 block w-full sm:text-sm border-gray-300 rounded-md px-3 py-2 outline-none"
					disabled={true}
					placeholder="Please login"
					value={$actor}
				/>
			</div>
		</div>

		<div>
			<label for="email" class="flex text-sm font-medium text-gray-700">To</label>
			<div class="mt-1">
				<input
					type="text"
					name="to"
					id="to"
					class="shadow-sm border focus:ring focus:ring-purple-500 focus:border-purple-500 block w-full sm:text-sm border-gray-300 rounded-md px-3 py-2 outline-none"
					placeholder="e.g. token.burn"
					bind:value={to}
				/>
			</div>
		</div>
		<div>
			<label for="email" class="flex text-sm font-medium text-gray-700">Amount</label>
			<div class="mt-1">
				<input
					type="text"
					name="amount"
					id="amount"
					class="shadow-sm border focus:ring focus:ring-purple-500 focus:border-purple-500 block w-full sm:text-sm border-gray-300 rounded-md px-3 py-2 outline-none"
					placeholder="e.g. 1.3"
					bind:value={amount}
				/>
			</div>
		</div>

		<div class="flex justify-center">
			<!-- svelte-ignore a11y_click_events_have_key_events -->
			<!-- svelte-ignore a11y_no_static_element_interactions -->
			<div
				class="cursor-pointer whitespace-nowrap bg-purple-100 border border-transparent rounded-md py-2 px-4 inline-flex items-center justify-center text-base font-medium text-purple-600 hover:bg-purple-200"
				onclick={() => transfer({ to, amount })}
			>
				Transfer
			</div>
		</div>
	</div>
</div>
